config:
  backup: true
  create: true
  dotpath: dotfiles
  import_variables:
  - theme.yaml
dotfiles:
  f_config:
    src: config/sway/config
    dst: ~/.config/sway/config
    actions:
    - check_package sway
    - check_package sway-backgrounds
    - check_package swaybg
    - check_package swayidle
    - check_package swaylock
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  f_mako_config:
    src: config/mako/config
    dst: ~/.config/mako/config
  f_terminator_config:
    src: config/terminator/config
    dst: ~/.config/terminator/config
    actions:
    - check_package terminator
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    actions:
    - check_package neovim
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    actions:
    - check_package git
    - check_package zsh
    - install_z
    - install_fzf
    - install_oh_my_zsh
profiles:
  mm:
    dotfiles:
    - f_config
    - d_waybar
    - f_mako_config
    - f_terminator_config
    - d_nvim
    - f_zshrc
    actions:
    - copy_bg
actions:
  pre:
    copy_bg: cp {{@@ _dotdrop_dotpath @@}}/bgs/{{@@ backgrond_image @@}} ~/.config/bg.jpg && convert -brightness-contrast -10x0 -blur 10x10 {{@@ _dotdrop_dotpath @@}}/bgs/{{@@backgrond_image @@}} ~/.config/lock.jpg
    check_package: dpkg -s {0} | grep installed
  post:
    install_fzf: if [ ! -d ~/.fzf ]; then git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf; bash ~/.fzf/install --key-bindings --completion --no-update-rc; fi
    install_oh_my_zsh: if [ ! -d ~/.oh-my-zsh ]; then sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"; fi
    install_z: if [ ! -f ~/.bin/z ]; then mkdir -p ~/bin && curl -s -o ~/bin/z.sh https://raw.githubusercontent.com/rupa/z/master/z.sh; fi
